version: "3.9"

services:
  api:
    build: .
    container_name: api-country-information
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/country_db?schema=public"
      NODE_ENV: production
    depends_on:
      - db
    volumes:
      - .:/app  

  db:
    image: postgres:16
    container_name: country-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: country_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
